### ISSUE TITLE
Error when running on Device (iPhone 6 Plus)

### ISSUE THREAD

**Issue by gotnull** [raulriera/TextFieldEffects#9]
It runs fine on the simulator and compiles fine on both the simulator and the device. But when I run the app on the device I get the following error:

dyld: Library not loaded: @rpath/TextFieldEffects.framework/TextFieldEffects
  Referenced from: /private/var/mobile/Containers/Bundle/Application/DD8E223B-5A3C-47AE-BA55-7F030765D4E5/TextFieldsDemo.app/TextFieldsDemo
  Reason: image not found
(lldb)

**Comment by raulriera** [comment]
May be a silly question but, are you using the TextFieldsDemo target and not the framework one? it selects by default the framework

**Comment by raulriera** [comment]
Oops, forgot to embed the binary to the target. Thanks

**Comment by gotnull** [comment]
No problem. I'll test it out tomorrow. Thanks.

On Thursday, March 12, 2015, Raul Riera <notifications@github.com> wrote:

> Oops, forgot to embed the binary to the target. Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raulriera/TextFieldEffects/issues/9#issuecomment-78447135>
> .
>


-- 
Sent from my iPhone (apologies for any typos or brevity).

**Comment by raulriera** [comment]
Fixed in 7879b21506848d298c66e23ef121de1edbf32559 thanks!

**Comment by gotnull** [comment]
Fulvio Cusumano has sent you a message via Indiegogo about the Buddy. The Dog Collar Re-Imagined campaign.

Hey,

I'm reaching out to ask for your support for my product "Buddy. The Dog Collar Re-Imagined". We're running a campaign on Indiegogo at the moment and I'd love your support.

https://www.indiegogo.com/projects/buddy-the-dog-collar-re-imagined

There are two ways to help:

1. Contribute - even small contributions raise their popularity and give them more visibility on the site.

2. Post to Facebook - in the end, the more people hear about them, the more likely they are to meet their target.

Thank you!

Fulvio Cusumano
http://www.squeakerdogs.com

Help the "Buddy. The Dog Collar Re-Imagined" campaign reach its goal today!

**Comment by raulriera** [comment]
Wut? 😅

**Comment by simonbogh** [comment]
I still get this error with v1.1.0. Do you experience this as well?

**Comment by raulriera** [comment]
Can you share some more info @simonbogh ? how are you setting up the library?

**Comment by simonbogh** [comment]
Sure.

I use Objective-C in my project and I had this working before upgrading to Xcode 7. My deployment target is iOS 8.0.

I use cocoapods as per the guide
use_frameworks!
pod "TextFieldEffects"

My test device is an iPhone 5 running iOS 9.1. 

The funny thing is that it works fine if I run the simulator e.g. with an iPhone 6S running 9.1 and also iPhone 5 running 8.1, but not on the real device, then I get the above error.

**Comment by raulriera** [comment]
Are you able to run the Example project in a device?
